# Generated by Django 3.1.1 on 2020-10-31 15:33

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('checkout', '0002_auto_20201017_1452'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='productorder',
            name='has_plan',
        ),
    ]
