# Generated by Django 3.1.1 on 2020-09-11 18:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('checkout', '0002_auto_20200910_1113'),
    ]

    operations = [
        migrations.AddField(
            model_name='productorder',
            name='original_shop_bag',
            field=models.TextField(default=''),
        ),
        migrations.AddField(
            model_name='productorder',
            name='stripe_pid',
            field=models.CharField(default='', max_length=254),
        ),
    ]
