# Generated by Django 3.1.1 on 2020-09-11 19:48

from django.db import migrations
import django_countries.fields


class Migration(migrations.Migration):

    dependencies = [
        ('checkout', '0003_auto_20200911_1854'),
    ]

    operations = [
        migrations.AlterField(
            model_name='productorder',
            name='country',
            field=django_countries.fields.CountryField(max_length=2),
        ),
    ]
