# Generated by Django 3.1.1 on 2020-09-11 20:08

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('user_profile', '0001_initial'),
        ('checkout', '0004_auto_20200911_1948'),
    ]

    operations = [
        migrations.AddField(
            model_name='productorder',
            name='user_profile',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='orders', to='user_profile.userprofile'),
        ),
    ]
