# Generated by Django 3.1.1 on 2020-09-14 10:49

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('checkout', '0005_productorder_user_profile'),
    ]

    operations = [
        migrations.RenameField(
            model_name='productorder',
            old_name='purchase_date',
            new_name='date',
        ),
    ]
