# Generated by Django 3.1.1 on 2020-09-20 20:50

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('nutrition', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='nutrition',
            name='description',
        ),
    ]
