# Generated by Django 3.1.1 on 2020-09-21 22:30

import autoslug.fields
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('subscriptions', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='plan',
            name='plan_name',
            field=autoslug.fields.AutoSlugField(editable=False, populate_from='plan_duration'),
        ),
    ]
