# Generated by Django 3.1.1 on 2020-10-14 13:28

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('subscriptions', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='plan',
            options={'verbose_name_plural': 'Plan'},
        ),
    ]
