# Generated by Django 3.1.1 on 2020-09-18 23:22

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Workouts',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('current_week', models.DecimalField(blank=True, decimal_places=0, max_digits=2, null=True)),
                ('main_goal', models.CharField(max_length=100)),
                ('workout_type', models.CharField(max_length=100)),
                ('training_level', models.CharField(max_length=100)),
                ('program_duration', models.CharField(max_length=100)),
                ('days_per_week', models.IntegerField(blank=True, null=True)),
                ('time_per_workout', models.CharField(max_length=100)),
                ('equipments_required', models.TextField(max_length=1000)),
                ('author_name', models.CharField(max_length=100)),
            ],
            options={
                'verbose_name_plural': 'workouts',
            },
        ),
    ]
