# Generated by Django 3.1.1 on 2020-10-31 17:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user_profile', '0003_auto_20201031_1533'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userprofile',
            name='has_plan',
            field=models.BooleanField(choices=[(True, 'Yes'), (False, 'No')], default=False),
        ),
    ]
