# Generated by Django 3.1.1 on 2020-09-07 12:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0005_auto_20200907_1123'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='image_file',
            field=models.ImageField(blank=True, null=True, upload_to=''),
        ),
        migrations.AlterField(
            model_name='product',
            name='sku',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
